name: FleetFlow CI/CD Pipeline

on:
  push:
    branches: [ "main", "master", "souhayb", "Ayoub_Branch" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Make Maven Wrapper Executable
        run: chmod +x mvnw

      - name: Build and Test with Maven
        run: ./mvnw clean verify

      - name: Prepare Artifact for Deployment
        uses: actions/upload-artifact@v4
        with:
          name: FleetFlow-Executable
          path: target/*.jar
          retention-days: 5
